version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/var/www/cuit_acm
    expose:
      - "3000"
    env_file: .env
    environment:
      RAILS_ENV: $RAILS_ENV
    links:
      - db
      - redis
      - spider
    depends_on:
      - db
      - redis
      - spider

  spider:
    build:
      context: ../ACM-Spider
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis

  db:
    image: mysql:5.6
    volumes:
      - ~/.db_data:/var/lib/mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $ACM_DATABASE_PASSWORD
      MYSQL_PASSWORD: $ACM_DATABASE_PASSWORD
  

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ../frontend:/var/www/cuit_acm/public/frontend
    links:
      - app
    ports:
      - "80:80"
    volumes_from:
      - app
